micronaut:
  application:
    name: personalfinancehelper
  server:
    port: ${SERVER_PORT}
datasources:
  default:
    url: ${DB_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
netty:
  default:
    allocator:
      max-order: 3
